### ISSUE TITLE
useFlags missing in 5.0.1

### ISSUE THREAD

**Issue by senser1** [garbles/flag#58]
Hi, most probably no bug but by intent; but useFlags hooks is no longer there in the 5.0.1 version. If by intent; any suggestions to get access to the list of all flags in a component?

**Comment by garbles** [comment]
This was by design because the backends are responsible for using the key path to return a scalar value.

Anecdotally, I felt that `useFlags` was an anti-pattern because it was slow and usually being done to lazily avoid having to include multiple `useFlag` hooks in a component.

I don't have plans to add it back right now, but happy to hear about your use case.

**Comment by senser1** [comment]
My use case is that I use flags to pass into a guard function part of my route definitions.  Something like: 

`path: '/secured', component: SecuredPage, guard: (flags) => flags.isAdmin`

**Comment by garbles** [comment]
Okay. Without knowing what the rest of your code does, I'd find a place to get the flags the routes need and then use that in the guard function. Would that work?

```ts
const isAdmin = useFlag('isAdmin');

// ...

const flags = {
  isAdmin
};

// ...

route.guard(flags);
```

**Comment by senser1** [comment]
Yes that would definitely work! Thanks for the great library. 👍
